name: idb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.7
  - pip
  - postgresql
  - nodejs
  - pip:
      - Flask
      - gunicorn
      - requests
      - beautifulsoup4
      - coverage
